# Generated by Django 2.2.4 on 2019-12-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='information',
            field=models.TextField(null=True),
        ),
    ]
