# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionnetworkevent',
            name='event_campaign',
        ),
        migrations.RemoveField(
            model_name='event',
            name='full_address',
        ),
        migrations.AddField(
            model_name='event',
            name='integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.Integration'),
        ),
        migrations.AddField(
            model_name='event',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.Integration'),
        ),
    ]
