# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_auto_20190801_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionnetworkeventcampaign',
            name='actionnetwork_integration',
        ),
        migrations.AlterField(
            model_name='actionnetworkevent',
            name='actionnetwork_id',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='actionnetworkeventcampaign',
            name='actionnetwork_id',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
