# Generated by Django 2.2.4 on 2019-08-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_auto_20190801_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionnetworkeventcampaign',
            name='browser_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
