# Generated by Django 2.2.4 on 2019-08-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_auto_20190801_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionnetworkeventcampaign',
            old_name='title',
            new_name='an_name',
        ),
        migrations.AddField(
            model_name='actionnetworkeventcampaign',
            name='an_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
