# Generated by Django 2.2.4 on 2019-08-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_auto_20190801_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionnetworkeventcampaign',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
