# Generated by Django 2.2.4 on 2019-08-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0009_auto_20190809_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilizeAmericaEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etl.Event')),
                ('description', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('high_priority', models.BooleanField(null=True)),
                ('visibility', models.CharField(max_length=100, null=True)),
                ('virtual_action_url', models.CharField(max_length=500, null=True)),
                ('featured_image_url', models.CharField(max_length=200, null=True)),
            ],
            bases=('etl.event',),
        ),
        migrations.CreateModel(
            name='MobilizeAmericaIntegration',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etl.Integration')),
                ('organization_id', models.IntegerField(null=True)),
            ],
            bases=('etl.integration',),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='original_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
