# Generated by Django 2.2.4 on 2019-08-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0010_auto_20190809_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilizeAmericaEventType',
            fields=[
                ('eventtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etl.EventType')),
                ('mobilize_event_type', models.CharField(max_length=200, null=True)),
            ],
            bases=('etl.eventtype',),
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='original_name',
        ),
        migrations.AddField(
            model_name='mobilizeamericaevent',
            name='timeslot_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
