# Generated by Django 2.2.4 on 2019-08-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0011_auto_20190809_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizeamericaeventtype',
            name='mobilize_america_integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.MobilizeAmericaIntegration'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.EventTypeMapping'),
        ),
        migrations.AlterUniqueTogether(
            name='mobilizeamericaeventtype',
            unique_together={('mobilize_event_type', 'mobilize_america_integration')},
        ),
    ]
