# Generated by Django 2.2.4 on 2019-08-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0012_auto_20190809_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizeamericaevent',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
