# Generated by Django 2.2.4 on 2019-08-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0013_mobilizeamericaevent_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypemapping',
            name='display_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mobilizeamericaevent',
            name='timeslot_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
